### ISSUE TITLE
problem with start() not loading components from cordova windows app

### ISSUE THREAD

**Issue by gtyamamoto** [altiva/altiva#18]
I am building a Windows 10 app with cordova but when I call the app.start( ) function from altiva,
it points to unknown location (mainfolder/components)  but as the cordova build all the files are in (mainfolder/www/components). so the only thing I did to fix this problem was changing the start: function ( ) from altiva.js at:
 
> Altiva.load.baseUrl= this.config.path + '/components/'; 
to:

> Altiva.load.baseUrl= this.config.path + '/www/components/'; 

Here's my app folder:
-images
-cordova
-build
-config.xml
-www
       ---components
       ---js
       ---css
       ---(other stuffs)
       ---index.html
  I also have tried to put components folder outside from www folder but still not working,I guess its the cordova that don't build automatically by default others paths in the app besides the default folders. So is there any other way to do this  changing of path for Altiva.load.baseUrl by not altering the altiva.js?

**Comment by paulocoghi** [comment]
First, thanks to use Altiva! Because of the pending launch of the site, I had no idea that someone was already using Altiva only with readme instructions.

Changing `Altiva.load.baseUrl` is a functionality that just needs to be documented. I'm working right now on it, not just the documentation, but working in a more refined solution, that will allow you to inform the base path of your application.

Thanks for the details! I will close this issue only when I've done the documentation, including the "base path" feature.

**Comment by paulocoghi** [comment]
We released the new Altiva 2.0 and refined the routing core to ensure that this problem doesn't occur anymore.

On our new tests, everything was smooth. We used [**Cocoon.io**](https://cocoon.io/) to facilitate the process, but Cordova is still used on the end.

I will close this issue but feel free to re-open it if necessary. :)
